/**
 * BuildABear.Java Defines the BuildABear class
 * which is a template for BuildABear objects
 */
public class BuildABear{
    // 3 sections in an object class
    private String type;
    private String name;
    private int fillLevel;
    private boolean hasSound;
    private String recording;
    private double price;
    //encapsulation: keeping program hiden from user
    //1. instance variables(data/attributes/fields)

    //2. constructors initialize values

    //3. Methods (Behaviors/Actions/what it can do)
}
